# Copyright 2022 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# public ssh key to add to the build server
ssh_auth_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKtF user@machine"

# folder where the templated YAML files result in
workdir: "~/buildserver" # directory to store all the required files

# admin workstation specific below until end of file
buildserver_name: "buildserver01"
buildserver_gcpsa_component_access: '{{ lookup("env", "GCPSA_COMACC_FILE") }}'
buildserver_gcpsa: "component-access.json"
buildserver_sakeyfolder: "{{ workdir }}/sakeys" # different home directory on jumphost or adminWS
buildserver_create_gsa: false

# vSphere/vCenter
buildserver_vc_fqdn: "{{ glb_vc_fqdn }}"
buildserver_vc_validate_cert: false
buildserver_vc_username: '{{ glb_vc_username }}'
buildserver_vc_password: '{{ glb_vc_password }}'
buildserver_vc_datacenter: "{{ glb_vc_datacenter }}"
buildserver_vc_datastore: "{{ glb_vc_datastore }}"
buildserver_vc_cluster: "{{ glb_vc_cluster }}"
buildserver_vc_network: "{{ glb_vc_network }}" # VM Network
buildserver_vc_folder: "{{ glb_vc_folder }}" # optional
buildserver_vc_respool: "{{ glb_vc_respool }}" # if default resourcePool use <buildserver_vc_cluster>/Resources

# Networking
buildserver_nw_ipallocmode: "static" # dhcp or static
buildserver_nw_ip: "10.20.0.39" # IP address of VM
buildserver_nw_gw: "10.20.0.1" # gateway
buildserver_nw_cidr: "24" # netmask 24 or similar
buildserver_nw_dns: "{{ glb_dns }}" # list from group_vars/all
buildserver_ntp: "{{ glb_ntp[0] }}" # only one can be set default ntp.ubuntu.com

# Customizations
buildserver_custom_ca: '{{ lookup("file", lookup("env", "PRIV_REG_CA_FILE")) }}'

# Optional - when using private artifact repository
private_download_base: "{{ glb_private_download_base }}"
private_download_auth_header: "{{ glb_private_download_auth_header }}"
