# Copyright 2022 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ansible_ssh_common_args is required if your connection is: workstation (Ansible) -> jumphost -> Admin Workstation
# ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q anthosjumper@10.147.18.191"'

# SSH private key on jump host to connect to Admin Workstation
# ansible_ssh_private_key_file="/home/anthosjumper/.ssh/user_id_ed25519"

ansible_user: "ubuntu"

upload_artifactory_gcpsa_component_access: '{{ lookup("env", "GCPSA_COMACC_FILE") }}'
upload_artifactory_gcpsa: "component-access.json"
upload_artifactory_fqdn: "YOUR_SERVER_FQDN_HERE"
upload_artifactory_repo_name: "YOUR_REPO_NAME_HERE"
upload_artifactory_username: '{{ lookup("env", "PRIV_REG_USERNAME") }}'
upload_artifactory_password: '{{ lookup("env", "PRIV_REG_PASSWORD") }}'

govc_version: "0.27.5"
asm_asmcli_version: "1.13.4-asm.4-config2"

upload_artifactory_http_artifacts:
  - file: "govc-{{ govc_version }}.tar.gz"
    src: "https://github.com/vmware/govmomi/releases/download/v{{ govc_version }}/govc_Linux_x86_64.tar.gz"
    dst: "govc/{{ govc_version }}/govc-{{ govc_version }}.tar.gz"
  - file: "asmcli_{{ asm_asmcli_version }}"
    src: "https://storage.googleapis.com/csm-artifacts/asm/asmcli_{{ asm_asmcli_version }}"
    dst: "asm/{{ asm_asmcli_version }}/asmcli_{{ asm_asmcli_version }}"

upload_artifactory_gs_artifacts:
  - file: "gke-on-prem-admin-appliance-vsphere-{{ glb_anthos_version }}.ova"
    src: "gs://gke-on-prem-release/admin-appliance/{{ glb_anthos_version }}/gke-on-prem-admin-appliance-vsphere-{{ glb_anthos_version }}.ova"
    dst: "anthos/{{ glb_anthos_version }}/gke-on-prem-admin-appliance-vsphere-{{ glb_anthos_version }}.ova"
  - file: "gkeadm-{{ glb_anthos_version }}"
    src: "gs://gke-on-prem-release/gkeadm/{{ glb_anthos_version }}/linux/gkeadm"
    dst: "anthos/{{ glb_anthos_version }}/gkeadm-{{ glb_anthos_version }}"
  - file: "gkeadm-{{ glb_anthos_version }}.1.sig"
    src: gs://gke-on-prem-release/gkeadm/{{ glb_anthos_version }}/linux/gkeadm.1.sig
    dst: "anthos/{{ glb_anthos_version }}/gkeadm-{{ glb_anthos_version }}.1.sig"